version: "2.2"
services:
    ser2net:
        image: jbouwh/ser2net:latest
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        ports:
            - "3333:3333"
        network_mode: "bridge"
        restart: always
