version: "2.2"
services:
    ser2net:
        image: jbouwh/ser2net:latest
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        ports:
            - "3333:3333"
        network_mode: "bridge"
        restart: on-failure

    omnikdataloggerproxy:
        image: jbouwh/omnikdataloggerproxy:latest
        volumes:
            - /home/pi/docker/config/omnikdataloggerproxy/config.ini:/config.ini
        ports:
            - "10004:10004"
        network_mode: "bridge"
        restart: on-failure

