version: "3.3"
services:
    ser2net:
        image: jbouwh/ser2net:latest
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        ports:
            - target: 3333
              published: 3333
              protocol: tcp
              mode: host
        restart: on-failure
        deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
